export const root: string
export const rootContainer: string
export const leftContainer: string
export const rightContainer: string
export const contentContainer: string
export const contentParagraph: string
export const headerContainer: string
export const header: string
export const logo: string
export const image: string
export const imageContainer: string
export const promptContainer: string
export const promptParagraph: string
export const logoContainer: string
export const topVp: string
export const rightPadding: string
export const iconRow: string
export const iconContainer: string
export const dividerContainer: string
export const bookVectorContainer: string
export const bookVector: string