export const root: string
export const rootContainer: string
export const leftRootContainer: string
export const rightRootContainer: string
export const contentContainer: string
export const contentParagraph: string
export const headerContainer: string
export const header: string
export const logo: string
export const image: string
export const imageContainer: string
export const promptContainer: string
export const promptParagraph: string